### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jumpkick** [jumpkick/graphviz-preview#13]
[Enter steps to reproduce below:]

1. Save a file dot graph file
2. As the file renders the following exception is thrown

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [graphviz-preview](https://github.com/jumpkick/graphviz-preview) package, v0.3.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:774

TypeError: undefined is not a function
  at /Users/ged/.atom/packages/graphviz-preview/lib/graphviz-preview-view.coffee:72:41
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:996:20)
  at TextEditor.module.exports.TextEditor.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:583:26)
  at Pane.module.exports.Pane.saveItemAs (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:559:16)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:543:21)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:518:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:43.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:43.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:43.2.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -1:42.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:00.2.0 graphviz-preview:toggle (atom-text-editor.editor.is-focused)
     -0:53.9.0 core:cut (atom-text-editor.editor.is-focused)
     -0:33 graphviz-preview:toggle (atom-text-editor.editor.is-focused)
     -0:29.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:25.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:24.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:19.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:19.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:18.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:13.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "debugger",
      "debugger",
      "debugger"
    ],
    "useReactEditor": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.27.10
atom-html-preview, v0.1.10
file-icons, v1.5.6
graphviz-preview, v0.3.0
language-apache, v1.3.0
language-diff, v0.3.0
language-dot, v1.6.0
markdown-table-formatter, v2.5.2
minimap, v4.9.2
pdf-view, v0.22.0
script, v2.23.0

# Dev
No dev packages
```

**Comment by wysiib** [comment]
I sent you another pull request fixing the issues. Missed a renaming from Uri to URI.

**Comment by jumpkick** [comment]
Your pull worked, thanks.
